1969/update cookie package
barnardos/consent-banner pull request #5
Opened 2021-11-02 10:57 UTC by Ma9sha

@derekjohnson, can you Review the changes. I would also like to test it out locally if it is possible.

2021-11-05 16:19 UTC, derekjohnson requested changes

2021-11-05 16:19 UTC, derekjohnson commented on consent-banner.es5.js
> +    const focusableElements = consentBanner.querySelectorAll("a, button");
We can't use `const` in this file, it's not ES5. Use `var` instead.

2021-11-05 16:19 UTC, derekjohnson commented on consent-banner.es5.js
> +    var dl = l != 'dataLayer' ? '&l=' + l : '';
This is a good change 👍

2021-11-05 16:19 UTC, derekjohnson commented on consent-banner.es5.js
> +    cookieOverlay.addEventListener("click", e => {
Can't use arrow functions in ES5. This (and the next few instances) need to be changed to
```js
cookieOverlay.addEventListener("click", function(e) (
```

2021-11-05 16:46 UTC, derekjohnson commented
@Ma9sha due to scoping in JS the vars declared inside the `buildBanner()` function are `undefined` outside it. Because of this you need to move the declarations for `cookieOverlay` and `closeButton` outside the function like this:
```js
  var consentBanner = document.createElement('div');
  var rejectButton = buildButton('Reject');
  var acceptButton = buildButton('Accept');
  var cookieOverlay = document.createElement("div");
  var closeButton = document.createElement("button");
```

This is the same for all 3 files.

2021-11-08 09:57 UTC, Ma9sha commented
@derekjohnson , Thanks for the PR, updated the changes and its ready for another glance

2021-11-25 17:58 UTC, derekjohnson approved these changes

2021-11-26 09:20 UTC, merged